/* adl10-e.h    */
/*
 * Copyright 2008-2014  <coin.du@myirtech.com>
 *
 * 
 */

#ifndef __ADL10_E_H__
#define __ADL10_E_H__



#define SERVER_ID         17
#define INVALID_SERVER_ID 18

#define ADL10_E_BITS_ADDRESS 0x0
#define ADL10_E_BITS_NB 0x1


#define ADL10_E_INPUT_BITS_ADDRESS 0x0
#define ADL10_E_INPUT_BITS_NB 0x0

#define ADL10_E_REGISTERS_ADDRESS 0x0
#define ADL10_E_REGISTERS_NB_MAX 0x73

#define ADL10_E_INPUT_REGISTERS_ADDRESS 0x0
#define ADL10_E_INPUT_REGISTERS_NB 0




#define CURRENT_TOTOAL_ELECTRICITY_ADDRESS 0x00
#define CURRENT_TOTOAL_ELECTRICITY_NB 2
#define CURRENT_TOTOAL_ELECTRICITY_LEN 4
uint16_t CURRENT_TOTOAL_ELECTRICITY_REGISTERS_TAB[] = { 0x000A,0x000B };


#define VOLTAGE_ADDRESS 0x0B
#define VOLTAGE_NB 1
#define VOLTAGE_LEN 2
uint16_t VOLTAGE_REGISTERS_TAB[] = { 0x00DC };


#define CURRENT_ADDRESS 0x0C
#define CURRENT_NB 1
#define CURRENT_LEN 2
uint16_t CURRENT_REGISTERS_TAB[] = { 0x000a };



#define ACTIVITY_POWER_ADDRESS 0x0D
#define ACTIVITY_POWER_NB 1
#define ACTIVITY_POWER_LEN 2

#define REACTIVITY_POWER_ADDRESS 0x0E
#define REACTIVITY_POWER_NB 1
#define REACTIVITY_POWER_LEN 2

#define APPARENT_POWER_ADDRESS 0x0F
#define APPARENT_POWER_NB 1
#define APPARENT_POWER_LEN 2


#define POWER_FACTOR_ADDRESS 0x10
#define POWER_FACTOR_NB 1
#define POWER_FACTOR_LEN 2
uint16_t POWER_FACTOR_REGISTERS_TAB[] = { 0x0050 };



#define FREQUENCY_ADDRESS 0x11
#define FREQUENCY_NB 1
#define FREQUENCY_LEN 2

#define ADDRESS_ADDRESS 0x15
#define ADDRESS_NB 1
#define ADDRESS_LEN 2
uint16_t ADDRESS_REGISTERS_TAB[] = { 0x3401 };



#define METHOD_OF_TESTING_ADDRESS 0x48
#define METHOD_OF_TESTING_NB 1
#define METHOD_OF_TESTING_LEN 2

#define DEVICE_ID_ADDRESS 0x49
#define DEVICE_ID_NB 1
#define DEVICE_ID_LEN 6

#define FORWARD_REACTIVE_ELECTRIC_ENERGY_ADDRESS 0x4C
#define FORWARD_REACTIVE_ELECTRIC_ENERGY_NB 2
#define FORWARD_REACTIVE_ELECTRIC_ENERGY_LEN 4


#define REVERSING_REACTIVE_ELECTRIC_ENERGY_ADDRESS 0x4E
#define REVERSING_REACTIVE_ELECTRIC_ENERGY_NB 2
#define REVERSING_REACTIVE_ELECTRIC_ENERGY_LEN 4

#define FORWARD_ACTIVE_ELECTRIC_ENERGY_ADDRESS 0x68
#define FORWARD_ACTIVE_ELECTRIC_ENERGY_NB 2
#define FORWARD_ACTIVE_ELECTRIC_ENERGY_LEN 4

#define REVERSING_ACTIVE_ELECTRIC_ENERGY_ADDRESS 0x72
#define REVERSING_ACTIVE_ELECTRIC_ENERGY_NB 2
#define REVERSING_ACTIVE_ELECTRIC_ENERGY_LEN 4


#endif
